version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ard-server:latest
    container_name: ard-server-web
    ports:
      - "9090:9090"
    volumes:
      - .:/app
      - sensor_data:/app/data
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

volumes:
  sensor_data:
    name: ard_sensor_data 